[pytest]
addopts = -v --strict-markers -p no:launch_ros -p no:launch_testing -p no:ament_copyright -p no:ament_flake8 -p no:ament_lint -p no:ament_mypy -p no:ament_pep257 -p no:ament_xmllint
testpaths = tests
norecursedirs =
    lib
    lib64
    bin
    include
    share
    mujoco_menagerie
    gifs
    media
    markdowns
    .git
    __pycache__
    .pytest_cache
    .ruff_cache
    ci_artifacts
python_files = test_*.py
python_classes = Test*
python_functions = test_*
filterwarnings =
    ignore::DeprecationWarning
    ignore::UserWarning
